### ISSUE TITLE
Can't login - 401 unauthorized

### ISSUE THREAD

**Issue by masiorama** [PrestaShop/php-ps-info#1]
Hello there, I was able to use your script on my staging environment, while on production is not working at all, as it keeps asking for credentials, while I'm sure that those are right.
Any idea why it is not working?
Maybe it is related on the usage of $_SERVER in the checkAuth method?
Thanks in advance.

**Edit by @PierreRambaud:**
If the problem occurs, comment this line https://github.com/PrestaShop/php-ps-info/blob/master/phppsinfo.php#L499
```php
$info = new PhpPsInfo();
// $info->checkAuth();
```

**Comment by PierreRambaud** [comment]
Hi and thanks for your feedback.
What webserver are you using? Nginx ? Apache?

**Comment by masiorama** [comment]
Apache 2
PHP Version 7.0.31
Thanks!

**Comment by PierreRambaud** [comment]
Do you configure a new login or password? If yes, how to you do that?

**Comment by masiorama** [comment]
I tried both with original and changed credentials.
Sorry, I understand it is pretty difficult to find a solution in my case without further data.
I will check again a couple of times and then report back to you.
Thanks!

**Comment by PierreRambaud** [comment]
Still weird, I will try to investigate on tomorrow :)

**Comment by PierreRambaud** [comment]
@masiorama Still can't reproduce :( Are you on Linux?

**Comment by masiorama** [comment]
Yes, I'm on CentOS

**Comment by PierreRambaud** [comment]
This is maybe because you're running under CGI configuration. What version of PHP are you using?

**Comment by masiorama** [comment]
How can I check that? The PHP version is 7.0.31

**Comment by PierreRambaud** [comment]
Follow this link to know if you're running under CGI: https://stackoverflow.com/a/16414507

**Comment by PierreRambaud** [comment]
As I know, you need to disable the checkAuth, or play with Apache authentication system :/

**Comment by masiorama** [comment]
Can't on that shared hosting, I have very limited privilages.

>

**Comment by espacious** [comment]
Same here. But i can access if i dont change the password, but if i change the password to anything but not prestashop i get 401.

**Comment by PierreRambaud** [comment]
You can remove the check otherwise and add a htapasswd check instead

**Comment by espacious** [comment]
Ok, sorry for late response. Yes could be a solution, but did we found some info why this is happening?
I can provide logs and server configs... For me is happening on CentOS with latest Plesk with php 7.1.x or 7.2.x with php FPM enabled.

**Comment by metacreo** [comment]
The HTTP_AUTHORIZATION header removed by apache
Two ways to fix.
1) Add to .htaccess
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
2) Or add to apache config (may be virtualhost vonfig)

**Comment by PierreRambaud** [comment]
@metacreo Could you create a pull request to improve the readme?

**Comment by Gipielle** [comment]
I have the same problem

**Comment by Gipielle** [comment]
How can i remove password request by comment the file ?

Thanks

**Comment by PierreRambaud** [comment]
@Gipielle You can comment this line: https://github.com/PrestaShop/php-ps-info/blob/master/phppsinfo.php#L499
I will update the issue description :wink:

**Comment by Gipielle** [comment]
Thanks
