### ISSUE TITLE
MySQLi Extension - mysqlnd

### ISSUE THREAD

**Issue by fhukowal** [PrestaShop/php-ps-info#10]
Hello

I have a problem - an issue with my Host.
Your script has revealed in line 4 of your checking script as follows >> guote 
`MySQLi Extension	5.5	5.6	mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe3`
end of quote
(You can see that on attachment) 
![shot1](https://user-images.githubusercontent.com/62508001/77251076-7f766000-6c4c-11ea-94d5-a0f120669689.JPG)

Could you please confirm that my host server is OK and updated ? 
I mean - according to your script MySQLi extension shoul be 5.5 or 5.6 and it shows `mysqlnd 5.0.12-dev - 20150407 '
Is it OK and up to date or should i demand update ?

I have already ask them to update but they sais its OK- ??

Thank You in advance for your answer
Michał Kowal

**Comment by PierreRambaud** [comment]
It's ok, `mysqlnd 5.0.12-dev - 20150407` is the driver version when `5.5` or `5.6` are MySQL version :)

**Comment by PierreRambaud** [comment]
I'm closing it since everything should be ok  :)
