### ISSUE TITLE
Is it true php 7.3 is supported before prestashop 1.7.7 ?

### ISSUE THREAD

**Issue by arafatx** [PrestaShop/php-ps-info#11]
I'm on Prestashop 1.7.6 and I read in the official documentation here

https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

it said that PHP 7.3 supports only Prestashop 1.7.7 but this tool recommends that PS should be upgraded to PHP 7.3.

If this is true then, I'm going to remove PHP 7.2 in my server because the only reason I install PHP 7.2 along with the other latest PHP is because of prestashop. Can you verify this ? I forgot that this tool is made by Prestashop. So I should believe this tool right. Can someone update that documentation there ? It's very confusing.

**Comment by arafatx** [comment]
Ok, i found out that enabling php 7.3 on prestashop < 1.7.7 will trigger database error.

**Comment by PierreRambaud** [comment]
Hi,

Which tool are you talking about? :sweat_smile: 
If you look at this image on the devdocs, only 1.7.7.0 is compatible with PHP 7.3.
![image](https://user-images.githubusercontent.com/1462701/85261706-da4a6e00-b46c-11ea-986c-00925c6b7e5b.png)

Kind regards

**Comment by PierreRambaud** [comment]
Hi and thanks for your report.

This tool is only working with the latest version of PrestaShop, or the development one.
Here, this tool is built to be working with the 1.7.7.0.
You should only rely on the devdoc.
We should add a check for the targeted version of PS :thinking:

**Comment by arafatx** [comment]
Ok it has been 5 days since this comment, I'm using PHP 7.3 but I haven't notice any errors or code compatibility error with PHP 7.3

**Comment by matks** [comment]
> Ok it has been 5 days since this comment, I'm using PHP 7.3 but I haven't notice any errors or code compatibility error with PHP 7.3

Most of the code of PS 1.7.6 and PS 1.7.5 is php7.3-compliant.

Because let's not forget that php7.1, php7.2 and php7.3 are not *completely* different 😄 .

When we say "PS 1.7.6 works with php7.2 max (NOT php7.3)" it means "we have dedicated a huge amount of time and energy testing PS 1.7.6 with php7.2 in order to make sure EVERYTHING is php7.2 compliant"

And we will do the same huge amount of testing for PS 1.7.7 and php7.3 ; and for PS 1.7.8 and php7.4

Maybe PS 1.7.6 works well with php7.3 :) however we have not tested so we cannot guarantee it

**Comment by arafatx** [comment]
> Hi and thanks for your report.
> 
> This tool is only working with the latest version of PrestaShop, or the development one.
> Here, this tool is built to be working with the 1.7.7.0.
> You should only rely on the devdoc.
> We should add a check for the targeted version of PS 🤔


The latest version of prestashop for production is 1.7.6.7. So, I think this tool only aim to work for unreleased version or beta version of prestashop then. TQ. Yes, should add prestashop version check because I had the confusing of understanding the system requirement 2 years back because there was no documentation about system requirement. 

https://www.prestashop.com/forums/topic/806658-why-is-it-hard-to-understand-the-system-requirements/

**Comment by LocalHeroPro** [comment]
Same here https://github.com/PrestaShop/PrestaShop/issues/20999#issuecomment-693237508
