### ISSUE TITLE
toByte function issue

### ISSUE THREAD

**Issue by ashoot** [PrestaShop/php-ps-info#12]
Incorrect code in toByte function:
`    public function toBytes($val)
    {
        if (is_numeric($val)) {
            return $val;
        }

        **$val = trim($val);
        $val = (int) $val;
        switch (strtolower($val[strlen($val)-1])) {**
            case 'g':
                $val *= 1024;
                // continue
            case 'm':
                $val *= 1024;
                // continue
            case 'k':
                $val *= 1024;
        }

        return $val;
    }`

should be:
`
    public function toBytes($val)
    {
        if (is_numeric($val)) {
            return $val;
        }

        $val  = trim($val);
        $val2 = (int) $val;
        switch (strtolower($val[strlen($val)-1])) {
            case 'g':
                $val2 *= 1024;
                // continue
            case 'm':
                $val2 *= 1024;
                // continue
            case 'k':
                $val2 *= 1024;
        }

        return $val2;
    }

`

**Comment by PierreRambaud** [comment]
Hi @ashoot Could you confirm the problem is fixed with the Pull request #14 ?
