### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by BeReal86** [PrestaShop/php-ps-info#13]
I tried these trials in xampp php 7.3 and 7.4 versions. I also tried php 7.2 version on a normal server.

I have never been able to run the page.

<img width="618" alt="Screenshot_6" src="https://user-images.githubusercontent.com/16218107/89447927-80bdaa80-d75f-11ea-947e-a11eb1294398.png">

**Comment by PierreRambaud** [comment]
Hi,

You should read this part of the README. I don't see any PrestaShop instance in your directory, maybe put the file in `presta` directory?
https://github.com/PrestaShop/php-ps-info#usage

**Comment by BeReal86** [comment]
Hello @PierreRambaud ,

I was having some problems on localhost and xampp. I had to format the computer and did a clean install. I have had a chance to try it now and they work fine.
Cause problems arise with xampp. I think I need to use something else.

<img width="1223" alt="Screenshot_2" src="https://user-images.githubusercontent.com/16218107/89898498-81d05b00-dbe9-11ea-8601-205d95c50bf7.png">
