### ISSUE TITLE
Wrong usage instruction

### ISSUE THREAD

**Issue by LocalHeroPro** [PrestaShop/php-ps-info#16]
> 4. Open it up on your browser (http://your-domain.com/path-to-your-prestashop/phppsinfo.php).

When i put file inside main root of project, then I don't need to add `pwd` path of root project dir and have something like: `http://your-domain.com/phppsinfo.php`.
Please add some clarification to main README.md file what is proper way to use that tool.

**Comment by PierreRambaud** [comment]
Hi,
This is normal, it depends if your project has a subdirectory or not :thinking: 
It means you need to put this file in your prestashop directory.

Kind regards
