### ISSUE TITLE
does not want to connect on prestashop v1.7.6.8

### ISSUE THREAD

**Issue by thierry-laval** [PrestaShop/php-ps-info#18]
I bin deposited the file at the base of my prestashop folder. When I call the url I have the connection window of the php file but when I enter the passwords it refuses to open.
So I change the passwords in the php but it does the same. Any idea ?

**Comment by PierreRambaud** [comment]
Hi @thierry-laval

It's maybe due to your apache configuration.
The HTTP_AUTHORIZATION header is maybe removed by apache
Two ways to fix.
1) Add to .htaccess
    `RewriteCond %{HTTP:Authorization} .`
    `RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`
2) Or add to apache config (may be virtualhost config)
    `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

Otherwise, you can comment this line: https://github.com/PrestaShop/php-ps-info/blob/master/phppsinfo.php#L499

**Comment by thierry-laval** [comment]
Hi @PierreRambaud ,

on IONOS I cannot access and modify my apache configuration.
In the phppsinfo.php file if I replace the password and the login with nothing it's works ... 
But it's better with pasword so:
I applied solution 1 and the phppsinfo.php opens the connection popup but refuses to go further ...
I put my .htaccess back normally by removing solution 1 and it works .
And if I comment the line it doesn't change anything ...
Happy new year to you :-) from 17600

**Comment by PierreRambaud** [comment]
Really weird :sweat: 
I will try to investigate, could you give us more information about how IONOS is configured? CGI? FPM?

Oh, good news didn't know there are people from the PrestaShop ecosystem near me :sweat_smile: 
And Happy new year to you :)

**Comment by thierry-laval** [comment]
@Pierre Rambaud

Happy New Year's Day! Best wishes.

Ionos and Common Gateway Interface (the CGI):
https://www.ionos.fr/digitalguide/sites-internet/developpement-web/quest-ce-que-la-cgi/

And the settings (but it doesn't say anything about what you're looking for)
https://www.ionos.fr/assistance/hebergement/emploi-php-pour-un-projet-web/quels-parametres-php-puis-je-modifier/

The best is to contact them directly to ask them what is stuck, I am in mutualized and this is surely what is blocking. Then I can ask them but it will be next year because I work until 3 then I return to CM. But do not hesitate to make me a list and I will ask my Ionos advisor.

Prestashop:
We are Legion ... ;-)

**Comment by PierreRambaud** [comment]
I tried with a CGI environement. If I put:
```
RewriteCond %{HTTP:Authorization} .
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```
Inside my .htaccess or my virtual host, everything is working well :thinking:

**Comment by Progi1984** [comment]
Ping @thierry-laval

**Comment by stratboy** [comment]
Same issue here. Tried everything, doesn't work. Using mamp pro. How to?

**Comment by stratboy** [comment]
I 'hacked' it putting a return true on line 138.

**Comment by al-lucy** [comment]
Commenting line 496 works fine
$info->checkAuth();

**Comment by PierreRambaud** [comment]
I'm closing it as some workaround have been provided (and also how to properly configure CGI environement)
