### ISSUE TITLE
Let the script check the version of the prestashop.

### ISSUE THREAD

**Issue by morikoff** [PrestaShop/php-ps-info#22]
Gentlemen, for which version of the Prestashop this script?

**Comment by waleedelsafty** [comment]
just add this to the top of the file before class PhpPsInfo

> require_once 'vendor/autoload.php';
> $kernel = new AppKernel(_PS_MODE_DEV_?'dev':'prod', _PS_MODE_DEV_);
> define('_MY_PS_VERSION_', $kernel::VERSION);

and change the  getVersions() function to be like this :
  

>   public function getVersions()
>     {
>         $data = [
>             'Web server' => [$this->getWebServer()],
>             'PHP Type' => [
>                 strpos(PHP_SAPI, 'cgi') !== false ?
>                 'CGI with Apache Worker or another webserver' :
>                 'Apache Module (low performance)'
>             ],
>             'Prestashop Version' =>[_MY_PS_VERSION_]
>         ];
>

**Comment by waleedelsafty** [comment]
here you go

**Comment by AngelJEM9213** [comment]
how do I correct this issue https://github.com/PrestaShop/php-ps-info/issues/22

**Comment by matks** [comment]
Hello guys I dont fully understand the conversation but

- this tool is made to be used with latest prestashop version available
- latest prestashop version is version 8.1
