### ISSUE TITLE
Incorrect

### ISSUE THREAD

**Issue by LuigiMdg** [PrestaShop/php-ps-info#27]
Good evening, I think there is an error on this line.. It should be red or am I wrong?
![image](https://github.com/PrestaShop/php-ps-info/assets/18232125/e33b4200-70b7-420b-bcab-7d1590e3ebb1)

**Comment by matks** [comment]
Hello, I just checked release v1.2 and I dont see the problem so I guess you were using an old version 😉 

https://github.com/PrestaShop/php-ps-info/releases/tag/v1.2
