### ISSUE TITLE
Unable to log-in

### ISSUE THREAD

**Issue by radumchristian** [PrestaShop/php-ps-info#29]
Whatever I type in:
    const DEFAULT_PASSWORD = 'user';
    const DEFAULT_LOGIN = 'pass';
The script won't let me log-in

**Comment by VanityUrbaniec** [comment]
Have same problem.

**Comment by majel007** [comment]
Cannot log in with deafult login prestashop and pass prestashop

**Comment by VanityUrbaniec** [comment]
We have problem with PHP settings - now it works. And set login and psw on .php
<img width="284" alt="image" src="https://github.com/PrestaShop/php-ps-info/assets/148745703/335a388e-1117-4ed1-9294-630784e6e3f5">

**Comment by KloniraniDecak** [comment]
Thank you! It's working

**Comment by CharlieHarpers** [comment]
Same issue here, but deleting/ editing
login to:
  const DEFAULT_PASSWORD = ''; 
  const DEFAULT_LOGIN = '';
cannot be the right way.

Any further ideas?

**Comment by matks** [comment]
Hello guys, I just checked on php-ps-info v1.2 https://github.com/PrestaShop/php-ps-info/releases/tag/v1.2 and it works fine :/ 

If you check how the login/password check it's done by standard HTTP authentification, so I really dont know what could go wrong.

https://github.com/PrestaShop/php-ps-info/blob/master/phppsinfo.php#L146

You can maybe simply remove the lines in `checkAuth()` and put a `return;` 😉 to bypass the login step if you just use this tool for debug. I think the tool was protected for production usage.
