### ISSUE TITLE
Build a new release (v1.2) with last merged pull requests

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/php-ps-info#31]
[Official PrestaShop documentation](https://devdocs.prestashop-project.org/8/basics/installation/system-requirements/#how-to-verify-your-server-meets-prestashops-requirements) suggests to download [the latest version of php-ps-info](https://github.com/PrestaShop/php-ps-info/releases) that still is v1.1 since 2019 (5 years ago) and it missing the last 9 pull requests fixing many bugs, improvements and required version to comply with latest PrestaShop versions.

In my case I'm still facing issue with `Trying to access array offset on value of type int in phppsinfo.php on line 364` that is fixed in 2020 by #14.

Can you please build a new release including all last merged pull requests?

**Comment by matks** [comment]
Hello @Klemart3D indeed this repository got forgotten so PRs piled up without a release. I'll have a look at this next week. This repository is used in key modules of PrestaShop so if we perform a new release we need to validate properly the diff between the previous version and the old version, in order not to break anything.

If you can perform some validation as well on your side ;) that would be cool

**Comment by matks** [comment]
Done, with some delay 😅 https://github.com/PrestaShop/php-ps-info/releases/tag/v1.2
