### ISSUE TITLE
Recommends wrong PHP version

### ISSUE THREAD

**Issue by fulldecent** [PrestaShop/php-ps-info#34]
Correct version to recommend:

![Screenshot 2024-05-03 at 13 40 28](https://github.com/PrestaShop/php-ps-info/assets/382183/74ca945c-fbd9-43f2-abbe-d6f85ba688cc)

Actual version recommended:

![Screenshot 2024-05-03 at 13 40 08](https://github.com/PrestaShop/php-ps-info/assets/382183/86be2897-2eb2-4d37-aee1-05bb678ef994)

**Comment by matks** [comment]
I think you download v1.1 which was the latest release, built in 2019. I just performed a v1.2 release which is up-to-date 😉 

https://github.com/PrestaShop/php-ps-info/releases/tag/v1.2

**Comment by fulldecent** [comment]
Thank you, yes. All good now.
