### ISSUE TITLE
Add a check for 'php-mbstring'

### ISSUE THREAD

**Issue by Klemart3D** [PrestaShop/php-ps-info#4]
Hi,
Can you add a way to check if php extension `mbstring` is installed, because it seems necessary for PrestaShop 1.7 regarding this error: 

> Attempted to call function "mb_split" from the global namespace.

Also referenced in this issue: https://github.com/PrestaShop/PrestaShop/issues/9583
Or: https://github.com/PrestaShop/PrestaShop/issues/10689

**Comment by PierreRambaud** [comment]
Oh, didn't see your issues posted months ago :/
We will add this as soon as possible 👍
