### ISSUE TITLE
Directory section output

### ISSUE THREAD

**Issue by rss9090** [PrestaShop/php-ps-info#6]
I'm sorry but could you explain please to which processes/users should be writeable /var/cache and /var/logs ? On my webserver by default these folders are owned by root/wheel with 755 permissions set. To solve the issue I tried 1) to change permissions to 777 2) tried to chown root/wheel to www/www 3) tried to change logs directory at httpd.conf to /var/logs. But all these moves have no effect on your tool output.  In any case It still shows that  /var/cache  and var/logs aren't writeable.

**Comment by PierreRambaud** [comment]
In fact, when we say  ̀/var/cache` it's related to the root directory where you put your PrestaShop installation.
Example:
You put your PrestaShop on `/var/www/html/prestashop` it means you need to set the correct permission for `/var/www/html/prestashop/var/logs` and `/var/www/html/prestashop/var/cache`

**Comment by rss9090** [comment]
If I change in your code var/cache to cache - it passes the check. Considering the logs, if you mean Apache logs? They are moved outside public_html directory.

**Comment by PierreRambaud** [comment]
No it's the same as the cache directory, it's the logs directory stored in the PrestaShop installation.

**Comment by rss9090** [comment]
As far as I can see on a new PS 1.7.6.1 installation there are a var/logs and var/cache present and your tool says YES on them. But when I run your tool on an old 1.7.3.2  installation these were no such DIRs by default and that caused an error and misunderstandings.
P.S. I found another issue - any value of expose_php leads to always "YES"  check result. https://devdocs.prestashop.com/1.7/basics/installation/img/phppsinfo.jpg

**Comment by PierreRambaud** [comment]
This tool is build for latest PrestaShop version only.

**Comment by rss9090** [comment]
It would be very good if you add a kind of a warning about compatible PS version to the top of the output page of your tool to prevent further questions from community.
Considering expose_php check is it always "YES" result is Ok?

**Comment by metacreo** [comment]
BUG
PS 1.7.6.2
PHP 7.3.11 or PHP 7.1.33
All www root owned by www:www and have 755
Script shows:

# | Is Writable
-- | --
var/cache | No
var/logs | No
img | No
mails | No
modules | No
translations | No
upload | No
download | No
app/config | No
app/Resources/translations | No

**Comment by PierreRambaud** [comment]
What do you mean by `www-root`?

**Comment by metacreo** [comment]
Document root
sorry. this situation is only if phppsinfo.php placed in subfolder (example in admin).
getcwd() 
`    public function getDirectories()
    {
        $data = [];
        foreach ($this->requirements['directories'] as $directory) {
            $directoryPath = getcwd() . DIRECTORY_SEPARATOR . trim($directory, '\\/');
            $data[$directory] = [file_exists($directoryPath) && is_writable($directoryPath)];
        }
        return $data;
    }`

**Comment by PierreRambaud** [comment]
yes, php-ps-info must be placed in the document root of the PrestaShop installation. It can't guess where you installed PrestaShop.

**Comment by PierreRambaud** [comment]
I'm closing it since everything should be ok right now

**Comment by amir385276** [comment]
hi guys
how to writable my dirs to YES. i check my server and all of the dirs are 755 permission but in phppsinfo show NO
i don't know how to fix it
please help me thanks
![Uploading Clip_5.jpg…]()
